### PR TITLE
A web development project

### PR DESCRIPTION
**Pull request by deepaksanwaria**
It is a web development project which has a login and signup page with an email verification feature.

### CODE REVIEW

**Comment by dragonstin** [comment]
@deepaksanwaria Can you fix the images on the Readme?

**Comment by deepaksanwaria** [comment]
@dragonstin Can you please let me know what is the issue with the image so that I can fix it?

**Comment by dragonstin** [comment]
The images are not being display on the README. Change the link for the images on the project's folder.

**Comment by deepaksanwaria** [comment]
@dragonstin I have updated the images in README.md

**Pull request merged**
